export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const LOGOUT = "LOGOUT"

export const USER_LEDGER_REQUEST = "USER_LEDGER_REQUEST";
export const USER_LEDGER_SUCCESS = "USER_LEDGER_SUCCESS";
export const USER_LEDGER_FAILURE = "USER_LEDGER_FAILURE";


export const TRANSACTION_REQUEST = "TRANSACTION_REQUEST";
export const TRANSACTION_SUCCESS = "TRANSACTION_SUCCESS";
export const TRANSACTION_FAILURE = "TRANSACTION_FAILURE";


export const LEDGER_TRANSACTION_REQUEST = "LEDGER_TRANSACTION_REQUEST";
export const LEDGER_TRANSACTION_SUCCESS = "LEDGER_TRANSACTION_SUCCESS";
export const LEDGER_TRANSACTION_FAILURE = "LEDGER_TRANSACTION_FAILURE";

export const ADD_TRANSACTION ={
    REQUEST: "REQUEST",
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE"
}

export const AMOUNT_TYPE = "AMOUNT_TYPE";
export const PAGE_CHANGE = "PAGE_CHANGE";


